# Generated by Django 5.2.8 on 2025-11-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='ubicacion',
            new_name='descripcion',
        ),
    ]
